services:
  - type: web
    name: omnichain-assistant-web
    env: docker
    dockerCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: data-web
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: RERANK_ENABLED
        value: "false"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_COLLECTION_NAME
        value: layerzero-rag
      - key: OFT_API_KEY
        sync: false
      - key: SCAN_API_KEY
        sync: false

  - type: worker
    name: omnichain-assistant-bot
    env: docker
    numInstances: 1
    dockerCommand: python bot/bot.py
    autoDeploy: true
    disk:
      name: data-bot
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: RERANK_ENABLED
        value: "false"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_COLLECTION_NAME
        value: layerzero-rag
      - key: OFT_API_KEY
        sync: false
      - key: SCAN_API_KEY
        sync: false
